### ISSUE TITLE
Bug in PartialStructureSwitch copy constructor when running DeePER

### ISSUE THREAD

**Issue by gokeO** [donaldlab/OSPREY_refactor#22]
Please see my proposed fix in https://github.com/gokeO/OSPREY_refactor. Even after fixing the small copy constructor bug, the proper DOFs don't seem to get into the conf tree. In particular, I get the following error:

Exception in thread "main" java.lang.IllegalArgumentException: val shouldn't be NaN
	at edu.duke.cs.osprey.astar.conf.scoring.mplp.MessageVars.set(MessageVars.java:126)
	at edu.duke.cs.osprey.astar.conf.scoring.mplp.NodeUpdater.update(NodeUpdater.java:148)
	at edu.duke.cs.osprey.astar.conf.scoring.MPLPPairwiseHScorer.calc(MPLPPairwiseHScorer.java:34)
	at edu.duke.cs.osprey.astar.conf.scoring.MPLPPairwiseHScorer.calcDifferential(MPLPPairwiseHScorer.java:50)
	at edu.duke.cs.osprey.astar.conf.order.StaticScoreHMeanAStarOrder.scorePos(StaticScoreHMeanAStarOrder.java:79)
	at edu.duke.cs.osprey.astar.conf.order.StaticScoreHMeanAStarOrder.calcPosOrder(StaticScoreHMeanAStarOrder.java:46)
	at edu.duke.cs.osprey.astar.conf.order.StaticScoreHMeanAStarOrder.getNextPos(StaticScoreHMeanAStarOrder.java:33)
	at edu.duke.cs.osprey.astar.conf.ConfAStarTree.nextLeafNode(ConfAStarTree.java:126)
	at edu.duke.cs.osprey.astar.conf.ConfAStarTree.nextConf(ConfAStarTree.java:65)
	at edu.duke.cs.osprey.kstar.pfunc.ParallelConfPartitionFunction.calcWeightSumUpperBound(ParallelConfPartitionFunction.java:120)
	at edu.duke.cs.osprey.multistatekstar.ParallelPartitionFunction.init(ParallelPartitionFunction.java:39)
	at edu.duke.cs.osprey.multistatekstar.KStarScore.compute(KStarScore.java:59)
	at edu.duke.cs.osprey.control.MultiStateKStarDoer.calcStateKSScore(MultiStateKStarDoer.java:229)
	at edu.duke.cs.osprey.control.MultiStateKStarDoer.exhaustiveMultistateSearch(MultiStateKStarDoer.java:436)
	at edu.duke.cs.osprey.control.MultiStateKStarDoer.calcBestSequences(MultiStateKStarDoer.java:384)
	at edu.duke.cs.osprey.control.Main$6.run(Main.java:136)
	at edu.duke.cs.osprey.control.Main.main(Main.java:62)

**Comment by cuchaz** [comment]
In the Python branch, DOFs don't get copied anymore, so maybe this problem goes away entirely?
